#!/usr/bin/env python3
"Script generating random input for the linsolve program"

import numpy as np

_NR_VARIABLES = 4000


def main():
    "Main script functionality"
    out = np.empty((_NR_VARIABLES + 1, _NR_VARIABLES))
    out[:_NR_VARIABLES, :] = np.random.rand(_NR_VARIABLES, _NR_VARIABLES)
    out[_NR_VARIABLES, :] = np.random.rand(_NR_VARIABLES)
    np.savetxt('linsolve.in', out)


if __name__ == '__main__':
    main()
