#!/usr/bin/env python3
'''Solves a linear system of equations.'''
import sys
import os.path
import argparse
import linsolver.solvers as solvers
import linsolver.io as io

_DESCRIPTION = '''Solves the linear sytem of equation AX=B. It requires an
input file "linsolve.in", containing the coefficient matrix A (each line of A
should be written into a separate line) followed by the
right-hand-side vectors B. Each vector in B (column vector in the equation)
should be written into a separate *row* (as row vector) in the input. The
script writes a file "linsolve.out" containing the solution vectors X as row
vectors (one solution vector per line) or an error message if the solver
failed'''

_INPUT_FILE = 'linsolve.in'
_OUTPUT_FILE = 'linsolve.out'


def main():
    '''Main driver routine.'''
    args = _parse_arguments()
    infilepath = os.path.join(args.directory, _INPUT_FILE)
    try:
        aa, bb = io.read_input(infilepath)
    except OSError as exc:
        print("Failed to read input file '{}'".format(infilepath))
        print("Execption raised: {}".format(exc))
        sys.exit(1)
    outfilepath = os.path.join(args.directory, _OUTPUT_FILE)
    try:
        xx = solvers.gaussian_eliminate(aa, bb)
    except ValueError:
        io.write_error(outfilepath, "LINDEP", "Linearly dependent equations")
    else:
        io.write_result(outfilepath, xx)


def _parse_arguments():
    parser = argparse.ArgumentParser(description=_DESCRIPTION)
    msg = 'Directory, where input file is located and where output should be'\
        ' written to (default: .)'
    parser.add_argument('-d', '--directory', default='.', help=msg)
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    main()
